# Generated by Django 3.1.5 on 2021-03-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
