# Generated by Django 3.1.5 on 2021-03-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(default='2001-01-01'),
            preserve_default=False,
        ),
    ]
