# Generated by Django 3.1.5 on 2021-07-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoblentzNumbers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coblentznumbers',
            name='date',
            field=models.DateField(),
        ),
    ]
