# Generated by Django 3.1.5 on 2021-08-16 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CoblentzNumbers', '0002_auto_20210712_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='coblentznumbers',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
